version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: golang_next_ecommerce_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang_next_ecommerce_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: